name:  dart_web_components_examples
author: ted@tedsander.com
description:  Web Component Examples
version: 0.0.1

dependencies:
  #web_ui: any
  web_ui:
    path: /Users/ted/Documents/PolychromaticWorkspace/web-ui